name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/scritique-frontend || mkdir -p /home/ubuntu/scritique-frontend && cd /home/ubuntu/scritique-frontend
          git pull origin main || git clone https://github.com/scritique/scritique-frontend.git .
          npm ci || npm install
          npm run build
          sudo cp -r build/* /var/www/html/
          sudo systemctl reload nginx
          
 